apiVersion: apps/v1
kind: Deployment
metadata:
  name: hksyu-super-schedule
  labels:
    app: hksyu-super-schedule
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hksyu-super-schedule
  template:
    metadata:
      labels:
        app: hksyu-super-schedule
    spec:
      containers:
        - name: hksyu-super-schedule
          image: hksyu-super-schedule:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: ICP_NUMBER
              value: "皖ICP备2021010792号-1"
            - name: ICP_CHINA_ONLY
              value: "true"
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 64Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
